root: /
permalink: /:year-:month-:title/
markdown: rdiscount
pygments: true 
paginate: 5
excerpt_link: "阅读更多 &rarr;"

title: 格物堂
description: Statistics, Literature and Fantasy
author: dengyishuo
address: http://yishuo.org
subscribe_rss: /atom.xml
license: true
category_list: true
tag_cloud: true
links: true


#Generate css
#compass compile

